version: '2'

volumes:
    logs:
        driver: local
    mariadb:

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            DB_BACKEND_NAME: "testdb"
            DB_BACKEND_USER: "testuser"
            DB_BACKEND_PASSWORD: "testpassword"
            IM_ENVIRONMENT: "development"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        links:
            - 'mariadb'
    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/London"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: "testuser"
            MYSQL_PASSWORD: "testpassword"
            MYSQL_DATABASE: "testdb"

volumes:
    - ./scripts/dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql:ro
